### ISSUE TITLE
Issue downloading

### ISSUE THREAD

**Issue by KekSprite** [edbeeching/godot_rl_agents#172]
I wasn't sure if this had been asked or if this had anything to do with this but everytime I put in the command to download godot-rl I get this error and I don't know how to fix it or what to do about it. Some help would be nice, I've been at this for a bit 

>      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      CMake Error at CMakeLists.txt:17 (project):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\456el\rl\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\456el\rl\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\456el\rl\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 327, in <module>
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 264, in run
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\456el\AppData\Local\Temp\pip-build-env-enj49zki\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 235, in run
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.EXE', '-DPYTHON_INCLUDE_DIR=C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\\Include', '-DPYTHON_EXECUTABLE=C:\\Users\\456el\\rl\\Scripts\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp312-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.12', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\456el\\AppData\\Local\\Temp\\pip-install-kyu8mr0m\\onnx_a146f5fbddaa4bc79148527c13ca7968']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects

**Comment by Ivan-267** [comment]
Hello,

Could be something to do with the Python version or other dependencies perhaps.

Python tests pass with 3.8. 3.9, and 3.10.

If using conda, could you try to make a new env with Python 3.10 and see if it works?
E.g.:

`conda create --name gdrl python=3.10.10`
`conda activate gdrl`
`pip install godot-rl`

**Comment by KekSprite** [comment]
> Hello,
> 
> Could have something to do with the Python version or other dependencies perhaps.
> 
> Python tests pass with 3.8. 3.9, and 3.10.
> 
> If using conda, could you try to make a new env with Python 3.10 and see if it works? E.g.:
> 
> `conda create --name gdrl python=3.10.10` `conda activate gdrl` `pip install godot-rl`
> 
> If that's the cause, some changes to https://github.com/edbeeching/godot_rl_agents/blob/main/pyproject.toml could resolve it for different versions.

Oh yeah that worked perfectly, thanks for the help!
