### ISSUE TITLE
TypeError: '>=' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by ryash072007** [edbeeching/godot_rl_agents#31]
Traceback (most recent call last):
  File "C:\Users\ryash\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ryash\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ryash\Documents\Godot RL\try1\RL1\Scripts\gdrl.exe\__main__.py", line 7, in <module>
  File "C:\Users\ryash\Documents\Godot RL\try1\RL1\lib\site-packages\godot_rl\main.py", line 108, in main
    training_function(args, extras)
  File "C:\Users\ryash\Documents\Godot RL\try1\RL1\lib\site-packages\godot_rl\wrappers\stable_baselines_wrapper.py", line 78, in stable_baselines_training
    env = StableBaselinesGodotEnv()
  File "C:\Users\ryash\Documents\Godot RL\try1\RL1\lib\site-packages\godot_rl\wrappers\stable_baselines_wrapper.py", line 12, in __init__
    self.env = GodotEnv(port=port, seed=seed)
  File "C:\Users\ryash\Documents\Godot RL\try1\RL1\lib\site-packages\godot_rl\core\godot_env.py", line 44, in __init__
    self._get_env_info()
  File "C:\Users\ryash\Documents\Godot RL\try1\RL1\lib\site-packages\godot_rl\core\godot_env.py", line 235, in _get_env_info
    observation_spaces[k] = spaces.Discrete(v["size"])
  File "C:\Users\ryash\Documents\Godot RL\try1\RL1\lib\site-packages\gym\spaces\discrete.py", line 15, in __init__
    assert n >= 0
TypeError: '>=' not supported between instances of 'list' and 'int'

**Comment by ryash072007** [comment]
What do I do?

**Comment by ryash072007** [comment]
Fixed the issue
